### ISSUE TITLE
Nav-bar comum não autenticada

### ISSUE THREAD

**Issue by saviocamacam** [atlacontexto/lacroix-web-front#10]
Exibição da logo da ATLA com links para _landing_ de cada Perfil usuário do sistema:
- Alunos;
- Pais;
- Professores;
- Escolas;
- Municípios;

**Comment by saviocamacam** [comment]
@WillianRod esta issue serve para qualquer modificação ou melhoramento na nav-bar pública, ou seja, podemos fechá-la e reabri-la.

**Comment by WillianRod** [comment]
Não é mais necessário esta autenticação pois foi alterado o layout
