### ISSUE TITLE
Lançamento WEB em produção

### ISSUE THREAD

**Issue by saviocamacam** [atlacontexto/lacroix-web-front#16]
Versão principal da aplicação:
- [x] Disponibilização com Heroku Hobby;
- [x] Configuração DNS e SSL;
Endereço: https://www.atlaensino.com/

**Comment by hensou** [comment]
Se for só por questão subir uma aplicaçao em desenvolvimento acho que poderia fazer uma outra build da branch de desenvolvimento por exemplo
