### ISSUE TITLE
Estilizar página de "Signup"

### ISSUE THREAD

**Issue by saviocamacam** [atlacontexto/lacroix-web-front#25]
O que?
Foi criada uma rota/página específica para o cadastro de usuário, para deixar o processo de cadastro mais acessível;

---
Como?
A página de signup passa a exibir uma mensagem de incentivo direcionada para cada perfil:
- Todos os CTOs de landing pages, sejam botões do NavBar ou botões inferiores nas landings direcionam para a mesma rota ~/signup;
- A mensagem deve ser personalizada de acordo com o botão que o direcionou, ou seja, a mensagem de incentivo deve estar de acordo com a landing que o direcionou, exibir incentivo ao professor, se veio da landing professor;

--- 
Onde?
/client/src/app/auth/signup

**Comment by WillianRod** [comment]
Página de cadastro de usuário de forma genérica para alcançar todos os tipos de usuários do sistema em /auth/register
