### ISSUE TITLE
Criar model "News"

### ISSUE THREAD

**Issue by saviocamacam** [atlacontexto/lacroix-web-front#35]
O que?
Criar o model de Novidade, mudando a ideia simples de "postagem" de redes sociais comuns, ao se referir ao sistema como um ambiente de compartilhamento de eventos e notícias;

---
Como?
Criar um model com os campos:

- [x] Profile: como Object.Id especificando um perfil responsável pela Novidade;
- [x] Comments: um array de Object.id do tipo Comentário, para listar os comentários de uma novidade;
- [x] Votes: um array de  Object.Id do tipo de voto para definir os votos dados aquela Novidade;

---
Onde?
/models/news.js

**Comment by WillianRod** [comment]
Model criado em `/models/social/news.js`
