### ISSUE TITLE
Criar model "Comment"

### ISSUE THREAD

**Issue by saviocamacam** [atlacontexto/lacroix-web-front#36]
O quê?
Criar o model de comentário, a ser associado às Novidades ou como resposta de outros comentários.

---
Como?
Criar um model com os campos:

- [x] Profile: como Object.Id do tipo Perfil;
- [x] Answers: como array de Object.Id como auto-referência de Comment;
- [x] CountAnswers: contador de respostas;
- [x] Message: como string que leva o conteúdo do comentário
- [x] Votes: como array Object.Id que referencia Vote;
- [x] CountVotes: contador contador de Votos;

---
Onde?
/models/comment.js

**Comment by WillianRod** [comment]
Model criado em `/models/social/comment.js`
