### ISSUE TITLE
Fea: criar componente de controle de frequência de alunos

### ISSUE THREAD

**Issue by saviocamacam** [atlacontexto/lacroix-web-front#53]
O quê?

Criar componente 'Frequência' a ser servido na rota 'professor/turma/frequencia', acessado na navegação do professor na Árvore Turma/Frequência.

---
Como?

Criar o componente via comando

ng g componente students no diretório app/main/pages/private/professor/classroom

**Comment by WillianRod** [comment]
Componente criado em `app\main\private\professor\classroom\students`
