### ISSUE TITLE
Traduzir a interface do TinyMCE.

### ISSUE THREAD

**Issue by jeffmant** [atlacontexto/lacroix-web-front#56]
O quê?

Realizar a tradução da interface do TinyMCE.

---

Como?

Seguir os passos que a ferramenta dispõem em suas documentações.
https://www.tiny.cloud/docs/configure/localization/#language

**Comment by WillianRod** [comment]
Adicionar label no botão imprimir e colocar ele do lado do botão salvar no TinyMCE
