### ISSUE TITLE
Eliminar espaços vazios no array de anos das competências da BNCC.

### ISSUE THREAD

**Issue by jeffmant** [atlacontexto/lacroix-web-front#63]
O quê?

Como mostrado abaixo, a listagem de anos das competências está inserindo espaços vazios antes do dado em si.
{
    ...
        "ano" : [
                "1º",
                " 2º",
                " 3º",
                " 4º",
                " 5º"
        ],
   ...
}

---

**Comment by hensou** [comment]
Tinha esquecido de dar um `.strip()` para tirar os espaços kkkkk
Enviei o correto no telegrão! :]
